---
- name: Set up Jenkins agent on Ubuntu
  hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create a directory for the Jenkins agent
      file:
        path: /slave1
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'

    - name: Write secret to file
      copy:
        content: "5d61bc9cf192e894a0f6327016bdb61b43951b4182c7b9c28d1bd808bf93782f\n"
        dest: /slave1/secret-file
        owner: jenkins
        group: jenkins
        mode: '0644'

    - name: Download Jenkins agent jar
      get_url:
        url: http://localhost:8080/jnlpJars/agent.jar
        dest: /slave1/agent.jar
        owner: jenkins
        group: jenkins
        mode: '0755'

    - name: Create a systemd service for Jenkins agent
      copy:
        content: |
          [Unit]
          Description=Jenkins Agent
          After=network.target

          [Service]
          User=jenkins
          Group=jenkins
          ExecStart=/usr/bin/java -jar /slave1/agent.jar -url http://localhost:8080/ -secret @/slave1/secret-file -name slave1 -workDir /slave1
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/jenkins-agent.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable Jenkins agent service
      systemd:
        name: jenkins-agent
        state: started
        enabled: yes
