---
- name: Install SonarQube on Ubuntu
  hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: default-jdk
        state: present

    - name: Add SonarQube repository key
      apt_key:
        url: https://bintray.com/jfrog/artifactory-rpms/pubkey
        state: present

    - name: Add SonarQube repository
      apt_repository:
        repo: 'deb https://bintray.com/jfrog/artifactory-rpms/rpm /'
        state: present

    - name: Install SonarQube
      apt:
        name: sonarqube
        state: present

    - name: Start SonarQube service
      service:
        name: sonarqube
        state: started
        enabled: yes


    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
