---
- name: Install SonarQube on Ubuntu
  hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: default-jdk
        state: present

    - name: Install dependencies
      apt:
        name: 
          - gnupg
          - wget
        state: present

    - name: Add SonarQube GPG key
      shell: |
        wget -qO - https://download.sonarsource.com/sonarqube/release/sonarqube-8.9.0.43852.zip

    - name: Add SonarQube repository
      apt_repository:
        repo: "deb https://apt.sonarqube.org/latest stable main"
        state: present
        filename: "/etc/apt/sources.list.d/sonarqube.list"
    
    - name: Update apt cache after adding SonarQube repository
      apt:
        update_cache: yes

    - name: Install SonarQube
      apt:
        name: sonarqube
        state: present

    - name: Start and enable SonarQube service
      systemd:
        name: sonarqube
        state: started
        enabled: yes
