---
- name: Download and run Jenkins agent
  hosts: all
  tasks:
    - name: Download agent.jar
      shell: curl -sO http://localhost:8080/jnlpJars/agent.jar
      args:
        chdir: /path/to
 
    - name: Run Jenkins agent
      shell: >
        java -jar /path/to/agent.jar
        -url http://localhost:8080/
        -secret 5d61bc9cf192e894a0f6327016bdb61b43951b4182c7b9c28d1bd808bf93782f
        -name slave1
        -workDir /slave1
      args:
        chdir: /slave1
