---
- name: Install SonarQube on Ubuntu
  hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: default-jdk
        state: present

    - name: Download SonarQube GPG key
      get_url:
        url: "https://bintray.com/jfrog/artifactory-rpms/pubkey"
        dest: "/etc/apt/trusted.gpg.d/sonarqube.gpg"
        mode: '0644'
        force: yes

    - name: Add SonarQube repository
      apt_repository:
        repo: "deb http://downloads.sourceforge.net/project/sonar-pkg/deb binary/"
        state: present

    - name: Install SonarQube
      apt:
        name: sonarqube
        state: present

    - name: Start SonarQube service
      service:
        name: sonarqube
        state: started
        enabled: yes
