---
- name: Ensure Apache is installed and running
  hosts: localhost
  become: yes

  tasks:
    - name: Check if Apache is installed
      shell: "which httpd"
      register: apache_installed
      ignore_errors: yes

    - name: Install Apache
      apt:
        name: httpd
        state: present
      when: apache_installed.rc != 0

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes

